version: '3.9'

# GOAL : running docker compose and whole pawcon project gets running
# TO DO : refactor each service later
services:
  server : 
    # build specifies where the service's Dockerfile is. 
    build : ./server
    container_name: server # it becomes volume/container name
    image: nellow1102/pawcon:server # set a tag for image
    ports:
      - '3001:3001' # host:container
    stdin_open: true 
    tty: true
    restart: always
    volumes:
      - server:/server
  client : 
    build : ./client
    container_name: client
    image: nellow1102/pawcon:client # set a tag for image
    ports:
      - '3000:3000' 
    restart: always
    volumes:
      - client:/client

# top-level volume
volumes:
  server :
    driver: local
  client : 
    driver: local