version: '3.9'

# GOAL : running docker compose and whole pawcon project gets running
# TO DO : refactor each service later
services:
  server : 
    # build specifies where the service's Dockerfile is. 
    build : /server
    container_name: pawcon-server
    ports:
      - '3001:3001'
    stdin_open: true 
    tty: true