baseURL = 'https://docs-pawcon.netlify.app/'
languageCode = 'en-us'
title = 'PawCon docs'
theme = 'ananke'

[[menu.main]]
  name ="_setup"
  url = "/_setup/"

[[menu.main]]
  name ="web"
  url = "/web/"

[[menu.main]]
  name ="blockchain"
  url = "/blockchain/"

[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.101.0"