name: CD

on:
  push:

jobs:
  pawcon-docs:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install hugo
      - name: install netlify in CI
      - name: use netlify hook for CD
