name: Auto-label

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened
  project_card:
    types:
      - moved

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set docs label
        run: echo should set a documentation label

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'feature/docs/')
        with:
          labels: documentation

      - name: set feature label
        run: echo should set an enhancement label
        # corresponding to git hook branch naming convention

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'feature/')
        with:
          labels: |
            enhancement
            test

      - name: set bugfix label
        run: echo should set a bug label

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'bugfix/')
        with:
          labels: bug

      - name: set hotfix label
        run: echo should set a bug label

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'hotfix/')
        with:
          labels: bug

      - name: set backlog label
        run: echo should set a backlog label for project issue

      - name: set backlog label to issue
        run: echo should set a backlog label

      - uses: andymckay/labeler@1.0.4
        with:
          add-labels: 'backlog'
          ignore-if-labeled: true
